### ISSUE TITLE
Add lookup table mappings to ROS config

### ISSUE THREAD

**Issue by DFriend01** [UBCSailbot/controller#22]
### Purpose

We want the lookup table to be configurable, and as such, we can put the lookup table in the ROS config file used when launching. This is so we can load the data upon the node launching.

### Description

Changes will need to be made in both sailbot workspace and this repository.

**Changes in Sailbot Workspace:**
1. Add lookup table parameters to `globals.yaml`:

```yaml
# global parameters
/**:
...

# local_pathfinding parameters
mgp_main:
...

# controller parameters
wingsail_ctrl_node:
    ros__parameters:
        reynolds_number: [0.0, 1.0, 2.0]
        angle_of_attack: [0.0, 1.0, 2.0]
```

2. Add documentation about the parameters in the `README.md` file in the `config` directory.

**Changes in this repository:**

Modify the `__declare_ros_parameters` function in the wingsail controller node. See the boat simulator for an example on how to read in lists.

**Tests:**

The ROS node automatically prints all parameters it receives upon startup, but only in `debug` mode. When launching the node in `debug` mode, you should be able to see the parameter printed out in the logs.
